<?= $this->partial('partial/title', ['title' => $this->translate('Profile')]) ?>
<?php if ($this->user->getAvatar() !== null) {
    $avatar = $this->user->getAvatar();
} else {
    if ($this->user->getGender() === Zetta\ZendAuthentication\Entity\Enum\Gender::FEMALE) {
        $avatar = $this->thumbnail()->getGirlThumbnailPath();
    } else {
        $avatar = $this->thumbnail()->getDefaultThumbnailPath();
    }
    $avatar = str_replace('./public/', '', $avatar);
}
?>

<div class="card mb-4">
    <div class="card-body">
        <h2><?= $this->user->getName() ?></h2>

        <?php
        $userFieldset = $this->form->get('user');
        echo $this->form()->openTag($this->form);
        ?>
            <?= $this->formHidden($userFieldset->get('id')) ?>

            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="avatar" class="sr-only"><?= $this->translate('Avatar') ?></label>
                        <div class="text-center">
                            <div class="mx-auto" style="max-width: 202px; --aspect-ratio:1;">
                                <img id='avatar-preview' class="avatar img-thumbnail rounded-circle"
                                     src="<?= $this->basePath($avatar) ?>"
                                     alt="<?= $this->translate('Avatar') ?>">
                            </div>
                            <h6 class="my-2"><?= $this->translate('Upload a different photo...') ?></h6>
                            <input id="avatar-upload" type="file"
                                   name="<?= $userFieldset->get('avatar')->getName() ?>" style="display: none">
                            <label id="avatar-label" class="btn btn-secondary"
                                   for="avatar-upload"><?= $this->translate('Choose the file') ?></label>
                        </div>
                        <?= $this->formElementErrors($userFieldset->get('avatar')) ?>
                    </div>
                </div>
                <div class="col-sm-9">
                    <h5 class="card-title">
                        <i class="fa fa-user"></i>
                        <?= $this->translate('Update information') ?>
                    </h5>
                    <hr>

                    <?php
                    $userFieldset = $this->form->get('user');
                    echo $this->form()->openTag($this->form);
                    echo $this->formHidden($userFieldset->get('id'));
                    ?>
                    <?= $this->zettaFormRow($userFieldset->get('name')) ?>

                    <?= $this->zettaFormRow($userFieldset->get('username')) ?>

                    <?= $this->zettaFormRow($userFieldset->get('email')) ?>

                    <div class="form-group">
                        <label class="control-label" for="password"><?= $this->translate('Password') ?></label>
                        <input type="password" name="password" class="form-control" id="password"
                               placeholder="<?= $this->translate('Password') ?>" disabled value="password">
                        <a href="<?= $this->url(
                            $this->routes['password-change']['name'],
                            $this->routes['password-change']['params'],
                            $this->routes['password-change']['options'],
                            $this->routes['password-change']['reuseMatchedParams']
                        ) ?>"
                           class="help-block">
                            <?= $this->translate('Change password?') ?>
                        </a>
                    </div>

                    <?= $this->zettaFormRow($userFieldset->get('gender')) ?>

                    <?= $this->zettaFormRow($userFieldset->get('birthday')) ?>

                    <?= $this->zettaFormRow($userFieldset->get('bio')) ?>

                    <?= $this->formRow($this->form->get('submit-btn')) ?>
                </div>
            </div>
        <?= $this->form()->closeTag() ?>
    </div>
</div>

<?php $this->inlineScript()->captureStart();
echo <<<JS
uploadImg('avatar');
JS;
$this->inlineScript()->captureEnd();
?>
