<?php $this->headTitle($this->translate('Profile')); ?>
<h1 class="page-top-header">
    <?php echo $this->translate('Profile'); ?>
</h1>

<div class="row">
    <div class="col-lg-6">
        <div class="user-display">
            <div class="user-display-bg"></div>
            <div class="user-display-bottom">
                <div class="user-display-avatar"><img src="<?php echo $this->basePath($user->getAvatar()); ?>" alt="@<?php echo $user->getUsername(); ?>"></div>
                <div class="user-display-info">
                    <div class="name"><?php echo $user->getName() ?: $user->getUsername(); ?></div>
                    <div class="nick"><span class="fa fa-user"></span> <?php echo $user->getUsername(); ?></div>
                </div>
                <div class="row user-display-details">
                    <div class="col-12">
                        <div class="title">Email</div>
                        <div class="counter"><?php echo $user->getEmail(); ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header card-header-divider">
                <i class="fa fa-user"></i>
                <?php echo $this->translate('Update information'); ?>
            </div>
            <div class="card-body">
                <?php
                $userFieldset = $form->get('user');
                echo $this->form()->openTag($form);
                echo $this->formHidden($userFieldset->get('id'));
                ?>
                    <div class="form-group">
                        <label class="control-label" for="username"><?php echo $this->translate('Username'); ?></label>
                        <input name="username" class="form-control" placeholder="<?php echo $this->translate('Username'); ?>" disabled value="<?php echo $userFieldset->get('username')->getValue(); ?>">
                    </div>
                    <?php echo $this->formHidden($userFieldset->get('username')); ?>

                    <div class="form-group">
                        <label class="control-label" for="password"><?php echo $this->translate('Password'); ?></label>
                        <input type="password" name="password" class="form-control" placeholder="<?php echo $this->translate('Password'); ?>" disabled value="password">
                        <a href="<?php echo $this->url($routes['password-change']['name'], $routes['password-change']['params'], $routes['password-change']['options'], $routes['password-change']['reuseMatchedParams']); ?>" class="help-block">
                            <?php echo $this->translate('Change password?'); ?>
                        </a>
                    </div>

                    <?php echo $this->zettaFormRow($userFieldset->get('name')); ?>

                    <?php echo $this->zettaFormRow($userFieldset->get('email')); ?>

                    <div class="form-group">
                        <label><?php echo $this->translate('Avatar'); ?></label>

                        <div class="row">
                            <div class="col-5">
                                <img class="media-object" id='avatar-preview' width="192" height="192" src="<?php echo $this->basePath($user->getAvatar()); ?>"/>
                            </div>
                            <div class="col-7">
                                <input id="avatar-upload" type="file" name="<?php echo $userFieldset->get('avatar')->getName(); ?>" style="display: none">
                                <label id="avatar-label" class="btn btn-outline-secondary" for="avatar-upload"><?php echo $this->translate('Choose the file'); ?></label>
                                </input>
                            </div>
                        </div>
                        <?php echo $this->formElementErrors($userFieldset->get('avatar')); ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->formRow($form->get('submit-btn')); ?>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
</div>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
$('#avatar-upload').change(function () {
    if (this.files && this.files[0]) {
        var file = this.files[0];
        var reader = new FileReader();
        reader.onload = function (e) {
            var selectedImage = e.target.result;
            $('#avatar-preview').attr('src', selectedImage);
            $('#avatar-label').text(
                file.name.length > 12 ? file.name.substring(0, 12)+"..." : file.name
            );
        };
        reader.readAsDataURL(this.files[0]);
    }
});
JS;
$this->inlineScript()->captureEnd();
?>
