<?= $this->partial('partial/title', ['title' => $this->translate('Profile')]) ?>
<?php if ($this->user->getAvatar() !== null) {
    $avatar = $this->user->getAvatar();
} else {
    if ($this->user->getGender() === Zetta\ZendAuthentication\Entity\Enum\Gender::FEMALE) {
        $avatar = $this->thumbnail()->getGirlThumbnailPath();
    } else {
        $avatar = $this->thumbnail()->getDefaultThumbnailPath();
    }
    $avatar = str_replace('./public/', '', $avatar);
}
?>

<div class="card mb-4">
    <div class="card-body">
        <h2><?= $this->user->getName() ?></h2>

        <?= $this->form()->openTag($this->form) ?>
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="avatar" class="sr-only"><?= $this->translate('Avatar') ?></label>
                        <div class="text-center">
                            <div class="mx-auto" style="max-width: 202px; --aspect-ratio:1;">
                                <img id='avatar-preview' class="avatar img-thumbnail rounded-circle"
                                     src="<?= $this->basePath($avatar) ?>"
                                     alt="<?= $this->translate('Avatar') ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-9">
                    <h5 class="card-title">
                        <i class="fa fa-lock"></i>
                        <?= $this->translate('Change password') ?>
                    </h5>
                    <hr>

                    <?= $this->zettaFormRow($this->form->get('password-old')) ?>

                    <div class="form-group toogle-password<?= $this->form->get('password-new')->getMessages() !== [] ? ' has-error' : '' ?>">
                        <?= $this->formLabel($this->form->get('password-new')) ?>
                        <?php
                        if (count($this->form->get('password-new')->getMessages()) !== 0) {
                            $this->form->get('password-new')->setAttribute('class', $this->form->get('password-new')->getAttribute('class') . ' is-invalid');
                        }
                        echo $this->formElement($this->form->get('password-new')); ?>
                        <i class="fa btn-toogle-password" onclick="togglePassword('#password-change-password-new'); return false;"></i>
                        <?= $this->formElementErrors($this->form->get('password-new'), ['class' => 'invalid-feedback']) ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formRow($this->form->get('submit-btn')) ?>
                        <?= $this->translate('or') ?>
                        <a href="<?= $this->url(
                            $this->routes['account']['name'],
                            $this->routes['account']['params'],
                            $this->routes['account']['options'],
                            $this->routes['account']['reuseMatchedParams']
                        ) ?>">
                            <?= $this->translate('back to profile') ?>
                        </a>
                    </div>
                </div>
            </div>
        <?= $this->form()->closeTag() ?>
    </div>
</div>
