<?php echo $this->partial('partial/title', ['title' => $this->translate('Profile')]); ?>
<?php if ($user->getAvatar() !== null) {
    $avatar = $user->getAvatar();
} else {
    if ($user->getGender() === Zetta\ZendAuthentication\Entity\Enum\Gender::FEMALE) {
        $avatar = $this->thumbnail()->getGirlThumbnailPath();
    } else {
        $avatar = $this->thumbnail()->getDefaultThumbnailPath();
    }
    $avatar = str_replace('./public/', '', $avatar);
}
?>

<div class="card mb-4">
    <div class="card-body">
        <h2><?php echo $user->getName(); ?></h2>

        <?php echo $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="avatar" class="sr-only"><?php echo $this->translate('Avatar'); ?></label>
                        <div class="text-center">
                            <div class="mx-auto" style="max-width: 202px; --aspect-ratio:1;">
                                <img id='avatar-preview' class="avatar img-thumbnail rounded-circle"
                                     src="<?php echo $this->basePath($avatar); ?>"
                                     alt="<?php echo $this->translate('Avatar'); ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-9">
                    <h5 class="card-title">
                        <i class="fa fa-lock"></i>
                        <?php echo $this->translate('Change password'); ?>
                    </h5>
                    <hr>

                    <?php echo $this->zettaFormRow($form->get('password-old')); ?>

                    <div class="form-group toogle-password<?php echo $form->get('password-new')->getMessages() !== [] ? ' has-error' : ''; ?>">
                        <?php echo $this->formLabel($form->get('password-new')); ?>
                        <?php
                        if (count($form->get('password-new')->getMessages()) !== 0) {
                            $form->get('password-new')->setAttribute('class', $form->get('password-new')->getAttribute('class') . ' is-invalid');
                        }
                        echo $this->formElement($form->get('password-new')); ?>
                        <i class="fa btn-toogle-password" onclick="togglePassword('#password-change-password-new'); return false;"></i>
                        <?php echo $this->formElementErrors($form->get('password-new'), ['class' => 'invalid-feedback']); ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->formRow($form->get('submit-btn')); ?>
                        <?php echo $this->translate('or'); ?>
                        <a href="<?php echo $this->url($routes['account']['name'], $routes['account']['params'], $routes['account']['options'], $routes['account']['reuseMatchedParams']); ?>">
                            <?php echo $this->translate('back to profile'); ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
