<?php echo $this->partial('partial/title', ['title' => $this->translate('Profile')]); ?>

<div class="row">
    <div class="col-lg-6">
        <div class="user-display">
            <div class="user-display-bg"></div>
            <div class="user-display-bottom">
                <div class="user-display-avatar"><img src="<?php echo $this->basePath($user->getAvatar()); ?>" alt="@<?php echo $user->getUsername(); ?>"></div>
                <div class="user-display-info">
                    <div class="name"><?php echo $user->getName() ?: $user->getUsername(); ?></div>
                    <div class="nick"><span class="fa fa-user"></span> <?php echo $user->getUsername(); ?></div>
                </div>
                <div class="row user-display-details">
                    <div class="col-12">
                        <div class="title">Email</div>
                        <div class="counter"><?php echo $user->getEmail(); ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header card-header-divider">
                <i class="fa fa-lock"></i>
                <?php echo $this->translate('Change password'); ?>
            </div>
            <div class="card-body">
                <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->zettaFormRow($form->get('password-old')); ?>

                    <div class="form-group toogle-password<?php echo $form->get('password-new')->getMessages() !== [] ? ' has-error': ''; ?>">
                        <?php echo $this->formLabel($form->get('password-new')); ?>
                        <?php
                        if (count($form->get('password-new')->getMessages()) !== 0) {
                            $form->get('password-new')->setAttribute('class', $form->get('password-new')->getAttribute('class') . ' is-invalid');
                        }
                        echo $this->formElement($form->get('password-new')); ?>
                        <i class="fa btn-toogle-password" onclick="togglePassword('#password-change-password-new'); return false;"></i>
                        <?php echo $this->formElementErrors($form->get('password-new'), ['class' => 'invalid-feedback']); ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->formRow($form->get('submit-btn')); ?>
                        <?php echo $this->translate('or'); ?>
                        <a href="<?php echo $this->url($routes['account']['name'], $routes['account']['params'], $routes['account']['options'], $routes['account']['reuseMatchedParams']); ?>">
                            <?php echo $this->translate('back to profile'); ?>
                        </a>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
