<?php
$title = $this->translate('Recover password');
$this->headTitle($title);
?>

<div class="splash-container">
    <div class="card card-border-color card-border-color-primary">
        <div class="card-header">
            <a href="<?php echo $this->url($routes['home']['name'], $routes['home']['params'], $routes['home']['options'], $routes['home']['reuseMatchedParams']); ?>">
                <img src="<?php echo $this->basePath('img/brand.svg') ?>" height="48" class="logo-img" alt="logo">
            </a>
            <span class="splash-description"><?php echo $this->translate('Please reset your password.'); ?></span>
        </div>
        <div class="card-body">
            <?php echo $this->zettaFlashMessenger(); ?>

            <?php echo $this->form()->openTag($form); ?>
                <span class="splash-title pb-4"><?php echo $title ?></span>

                <div class="form-group">
                    <label><?php echo $this->translate('Email'); ?></label>
                    <p class="form-control" readonly><?php echo $user->getEmail(); ?></p>
                </div>

                <div class="form-group toogle-password<?php echo $form->get('password-new')->getMessages() !== [] ? ' has-error': ''; ?>">
                    <?php echo $this->formLabel($form->get('password-new')); ?>
                    <?php echo $this->formElement($form->get('password-new')); ?>
                    <i class="fa btn-toogle-password" onclick="togglePassword('#password-change-password-new'); return false;"></i>
                    <?php echo $this->formElementErrors($form->get('password-new')); ?>
                </div>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('submit-btn')); ?>
                </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
    <div class="splash-footer">
        <span>
            <?php echo $this->translate('Already have an account?'); ?>
            <a href="<?php echo $this->url($routes['signin']['name'], $routes['signin']['params'], $routes['signin']['options'], $routes['signin']['reuseMatchedParams']); ?>">
                <?php echo $this->translate('Please login'); ?>
            </a>
        </span>
    </div>
</div>
