<?php
$title = $this->translate('Recover password');
$this->headTitle($title);
?>

<div class="splash-container">
    <div class="card card-border-color card-border-color-primary">
        <div class="card-header">
            <a href="<?= $this->url(
                $this->routes['home']['name'],
                $this->routes['home']['params'],
                $this->routes['home']['options'],
                $this->routes['home']['reuseMatchedParams']
            ) ?>">
                <img src="<?= $this->basePath('img/brand.svg') ?>" height="48" class="logo-img" alt="<?php $this->translate('Laminas Skeleton App') ?>">
            </a>
            <span class="splash-description"><?= $this->translate('Please reset your password.') ?></span>
        </div>
        <div class="card-body">
            <?= $this->zettaFlashMessenger() ?>

            <?= $this->form()->openTag($this->form) ?>
                <span class="splash-title pb-4"><?= $title ?></span>

                <div class="form-group">
                    <label><?= $this->translate('Email') ?></label>
                    <p class="form-control-plaintext"><?= $this->user->getEmail() ?></p>
                </div>

                <div class="form-group toogle-password<?= $this->form->get('password-new')->getMessages() !== [] ? ' has-error' : '' ?>">
                    <?= $this->formLabel($this->form->get('password-new')) ?>
                    <?= $this->formElement($this->form->get('password-new')) ?>
                    <i class="fa btn-toogle-password" onclick="togglePassword('#password-change-password-new'); return false;"></i>
                    <?= $this->formElementErrors($this->form->get('password-new')) ?>
                </div>

                <div class="form-group">
                    <?= $this->formRow($this->form->get('submit-btn')) ?>
                </div>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
    <div class="splash-footer">
        <span>
            <?= $this->translate('Already have an account?') ?>
            <a href="<?= $this->url(
                $this->routes['signin']['name'],
                $this->routes['signin']['params'],
                $this->routes['signin']['options'],
                $this->routes['signin']['reuseMatchedParams']
            ) ?>">
                <?= $this->translate('Please login') ?>
            </a>
        </span>
    </div>
</div>
