<?php
$title = $this->translate('Sign up');
$this->headTitle($title);
?>

<div class="signin-img text-center">
    <a class="signin-logo" href="<?php echo $this->url($routes['home']['name'], $routes['home']['params'], $routes['home']['options'], $routes['home']['reuseMatchedParams']); ?>">
        <img src="<?php echo $this->basePath('img/brand.svg') ?>" height="128" alt="<?php echo $this->translate('Home'); ?>">
    </a>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title text-center"><?php echo $title ?></h3>
    </div>
    <div class="panel-body">
        <?php echo $this->zettaFlashMessenger(); ?>
        <?php echo $this->form()->openTag($form); ?>
        <fieldset>
            <?php echo $this->zettaFormRow($form->get('email')); ?>
            <div class="row">
                <div class="col-xs-6">
                    <!-- Change this to a button or input when using this as a form -->
                    <?php echo $this->formRow($form->get('submit-btn')); ?>
                </div>
                <div class="col-xs-6">
                    <div><?php echo $this->translate('Already have an account?'); ?></div>

                    <strong>
                        <a href="<?php echo $this->url($routes['signin']['name'], $routes['signin']['params'], $routes['signin']['options'], $routes['signin']['reuseMatchedParams']); ?>">
                            <?php echo $this->translate('Please login'); ?>
                        </a>
                    </strong>
                </div>
            </div>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>