<?php
$title = $this->translate('Recover password');
$this->headTitle($title);
?>

<div class="splash-container">
    <div class="card card-border-color card-border-color-primary">
        <div class="card-header">
            <a href="<?php echo $this->url($routes['home']['name'], $routes['home']['params'], $routes['home']['options'], $routes['home']['reuseMatchedParams']); ?>">
                <img src="<?php echo $this->basePath('img/brand.svg') ?>" height="48" class="logo-img" alt="logo">
            </a>
            <span class="splash-description"><?php echo $this->translate('Forgot your password?'); ?></span>
        </div>
        <div class="card-body">
            <?php echo $this->zettaFlashMessenger(); ?>

            <?php echo $this->form()->openTag($form); ?>
                <p class="small">Don't worry, we'll send you an email to reset your password.</p>

                <?php echo $this->zettaFormRow($form->get('email')); ?>

                <p class="pt-1 pb-4 small">
                    <?php echo $this->translate('Don\'t remember your email?'); ?>
                    <a href="mailto:admin@z.com"><?php echo $this->translate('Contact Support'); ?></a>.
                </p>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('submit-btn')); ?>
                </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
    <div class="splash-footer">
        <span>
            <?php echo $this->translate('Already have an account?'); ?>
            <a href="<?php echo $this->url($routes['signin']['name'], $routes['signin']['params'], $routes['signin']['options'], $routes['signin']['reuseMatchedParams']); ?>">
                <?php echo $this->translate('Please login'); ?>
            </a>
        </span>
    </div>
</div>
