<?php
$title = $this->translate('Recover password');
$this->headTitle($title);
?>

<div class="splash-container">
    <div class="card card-border-color card-border-color-primary">
        <div class="card-header">
            <a href="<?= $this->url(
                $this->routes['home']['name'],
                $this->routes['home']['params'],
                $this->routes['home']['options'],
                $this->routes['home']['reuseMatchedParams']
            ) ?>">
                <img src="<?= $this->basePath('img/brand.svg') ?>" height="48" class="logo-img" alt="<?php $this->translate('Laminas Skeleton App') ?>">
            </a>
            <span class="splash-description"><?= $this->translate('Forgot your password?') ?></span>
        </div>
        <div class="card-body">
            <?= $this->zettaFlashMessenger() ?>

            <?= $this->form()->openTag($this->form) ?>
                <p class="small">Don't worry, we'll send you an email to reset your password.</p>

                <?= $this->zettaFormRow($this->form->get('email')) ?>

                <?= $this->zettaFormRow($this->form->get('captcha')) ?>

                <p class="pt-1 pb-4 small">
                    <?= $this->translate('Don\'t remember your email?') ?>
                    <a href="mailto:admin@z.com"><?= $this->translate('Contact Support') ?></a>.
                </p>

                <div class="form-group">
                    <?= $this->formRow($this->form->get('submit-btn')) ?>
                </div>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
    <div class="splash-footer">
        <span>
            <?= $this->translate('Already have an account?') ?>
            <a href="<?= $this->url(
                $this->routes['signin']['name'],
                $this->routes['signin']['params'],
                $this->routes['signin']['options'],
                $this->routes['signin']['reuseMatchedParams']
            ) ?>">
                <?= $this->translate('Please login') ?>
            </a>
        </span>
    </div>
</div>
