<?php
$title = $this->translate('Sign in');
$this->headTitle($title);
?>

<div class="signin-img text-center">
    <a class="signin-logo" href="<?php echo $this->url($routes['home']['name'], $routes['home']['params'], $routes['home']['options'], $routes['home']['reuseMatchedParams']); ?>">
        <img src="<?php echo $this->basePath('img/logo128.png') ?>" alt="<?php echo $this->translate('Home'); ?>"/>
    </a>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title text-center"><?php echo $title ?></h3>
    </div>
    <div class="panel-body">
        <?php echo $this->zettaFlashMessenger(); ?>
        <?php echo $this->form()->openTag($form); ?>
        <fieldset>
            <?php echo $this->zettaFormRow($form->get('username')); ?>
            <?php echo $this->zettaFormRow($form->get('password')); ?>

            <div class="row">
                <div class="col-xs-6">
                    <?php echo $this->zettaFormRow($form->get('remember-me'), 'append'); ?>
                </div>
                <div class="col-xs-6">
                    <div class="form-group">
                        <a href="<?php echo $this->url($routes['recover']['name'], $routes['recover']['params'], $routes['recover']['options'], $routes['recover']['reuseMatchedParams']); ?>">
                            <?php echo $this->translate('Forgotten password'); ?>
                        </a>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-6">
                    <!-- Change this to a button or input when using this as a form -->
                    <?php echo $this->formRow($form->get('submit-btn')); ?>
                </div>
                <div class="col-xs-6">
                    <div><?php echo $this->translate('Don\'t have an account?'); ?></div>

                    <strong>
                        <a href="<?php echo $this->url($routes['signup']['name'], $routes['signup']['params'], $routes['signup']['options'], $routes['signup']['reuseMatchedParams']); ?>">
                            <?php echo $this->translate('Sign up'); ?>
                        </a>
                    </strong>
                </div>
            </div>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>