<?php
$title = $this->translate('Sign in');
$this->headTitle($title);
?>

<div class="splash-container">
    <div class="card card-border-color card-border-color-primary">
        <div class="card-header">
            <a href="<?= $this->url(
                $this->routes['home']['name'],
                $this->routes['home']['params'],
                $this->routes['home']['options'],
                $this->routes['home']['reuseMatchedParams']
            ) ?>">
                <img src="<?= $this->basePath('img/brand.svg') ?>" height="48" class="logo-img" alt="<?php $this->translate('Laminas Skeleton App') ?>">
            </a>
            <span class="splash-description"><?= $this->translate('Please enter your user information.') ?></span>
        </div>
        <div class="card-body">
            <?= $this->zettaFlashMessenger() ?>

            <?= $this->form()->openTag($this->form) ?>
                <span class="splash-title pb-4"><?= $title ?></span>

                <?= $this->zettaFormRow($this->form->get('username')) ?>

                <?= $this->zettaFormRow($this->form->get('password')) ?>

                <div class="form-group row login-tools">
                    <div class="col-6 login-remember">
                        <?= $this->zettaFormRow($this->form->get('remember-me'), 'append') ?>
                    </div>
                    <div class="col-6 login-forgot-password">
                        <a href="<?= $this->url(
                            $this->routes['recover']['name'],
                            $this->routes['recover']['params'],
                            $this->routes['recover']['options'],
                            $this->routes['recover']['reuseMatchedParams']
                        ) ?>">
                            <?= $this->translate('Forgotten password') ?>
                        </a>
                    </div>
                </div>
                <div class="form-group">
                    <?= $this->formRow($this->form->get('submit-btn')) ?>
                </div>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
    <div class="splash-footer">
        <span>
            <?= $this->translate('Don\'t have an account?') ?>
            <a href="<?= $this->url(
                $this->routes['signup']['name'],
                $this->routes['signup']['params'],
                $this->routes['signup']['options'],
                $this->routes['signup']['reuseMatchedParams']
            ) ?>">
                <?= $this->translate('Sign up') ?>
            </a>
        </span>
    </div>
</div>
