<?php
$title = $this->translate('Sign in');
$this->headTitle($title);
?>

<div class="splash-container">
    <div class="card card-border-color card-border-color-primary">
        <div class="card-header">
            <a href="<?php echo $this->url($routes['home']['name'], $routes['home']['params'], $routes['home']['options'], $routes['home']['reuseMatchedParams']); ?>">
                <img src="<?php echo $this->basePath('img/brand.svg') ?>" height="48" class="logo-img" alt="<?php $this->translate('ZF Skeleton App'); ?>">
            </a>
            <span class="splash-description"><?php echo $this->translate('Please enter your user information.'); ?></span>
        </div>
        <div class="card-body">
            <?php echo $this->zettaFlashMessenger(); ?>

            <?php echo $this->form()->openTag($form); ?>
                <span class="splash-title pb-4"><?php echo $title ?></span>

                <?php echo $this->zettaFormRow($form->get('username')); ?>

                <?php echo $this->zettaFormRow($form->get('password')); ?>

                <div class="form-group row login-tools">
                    <div class="col-6 login-remember">
                        <?php echo $this->zettaFormRow($form->get('remember-me'), 'append'); ?>
                    </div>
                    <div class="col-6 login-forgot-password">
                        <a href="<?php echo $this->url($routes['recover']['name'], $routes['recover']['params'], $routes['recover']['options'], $routes['recover']['reuseMatchedParams']); ?>">
                            <?php echo $this->translate('Forgotten password'); ?>
                        </a>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('submit-btn')); ?>
                </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
    <div class="splash-footer">
        <span>
            <?php echo $this->translate('Don\'t have an account?'); ?>
            <a href="<?php echo $this->url($routes['signup']['name'], $routes['signup']['params'], $routes['signup']['options'], $routes['signup']['reuseMatchedParams']); ?>">
                <?php echo $this->translate('Sign up'); ?>
            </a>
        </span>
    </div>
</div>
